In [22]:
from ESN import Reservoir
from narma import NARMA
from tools import gen_narma_nmse_filepath
import matplotlib.pyplot as plt
import numpy as np
import copy

In [6]:
classic1 = Reservoir(reservoir_size_=4, spatial_multiplexing_=32)
classic1.add_performance_task(NARMA(degree_=6))
classic1.generate_inputs([1000,3000,5000])

classic2 = Reservoir(reservoir_size_=128)
classic2.add_performance_task(NARMA(degree_=6))
classic2.generate_inputs([1000,3000,5000])

In [34]:
W1 = np.random.uniform(-1,1,(4,4))
W11 = 1 / np.abs(np.linalg.eigvals(W1)).max()
W111 = W11*W1

W2 = np.random.uniform(-1,1,(4,4))
W22 = 1 / np.abs(np.linalg.eigvals(W2)).max()
W222 = W22*W2

W3 = np.random.uniform(-1,1,(4,4))
W33 = 1 / np.abs(np.linalg.eigvals(W3)).max()
W333 = W33*W3

W4 = np.random.uniform(-1,1,(4,4))
W44 = 1 / np.abs(np.linalg.eigvals(W4)).max()
W444 = W44*W4

zero = np.zeros((16,16))

In [35]:
veet1 = [W1,W2,W3,W4]
veet2 = [W111,W222,W333,W444]

In [23]:
reservoir_size = 4
spatial_multiplex = 4

In [ ]:
W4[0:2,0:2]

array([[ 0.81096455, -0.63015669, -0.99350537, -0.61544898],
       [ 0.51637423,  0.01007066,  0.08860768, -0.40657905],
       [-0.6969649 , -0.50958518,  0.60490756, -0.26167468],
       [ 0.7885168 , -0.54025793, -0.21877197, -0.98531919]])

In [36]:
first_W = copy.copy(zero)
second_W = copy.copy(zero)

for i in range(spatial_multiplex):
    print(np.abs(np.linalg.eigvals(veet2[i])).max())
    first_W[i*reservoir_size:(i+1)*reservoir_size,i*reservoir_size:(i+1)*reservoir_size] = veet1[i]
    second_W[i*reservoir_size:(i+1)*reservoir_size,i*reservoir_size:(i+1)*reservoir_size] = veet2[i]

1.0
1.0000000000000002
0.9999999999999999
0.9999999999999999


In [38]:
np.abs(np.linalg.eigvals(second_W)).max()

np.float64(1.0000000000000002)

In [ ]:
unscaled_W_ = np.random.uniform(-1,1,(self.reservoir_size,self.reservoir_size))
scaling_factor_W_ = 1 / np.abs(np.linalg.eigvals(unscaled_W_)).max()
self.matrix_W = scaling_factor_W_*unscaled_W_

In [7]:
classic1.reservoir_state

array([[ 0.06547356, -0.85107703, -0.38427794, -0.61358873],
       [ 0.9103187 , -0.70868799, -0.04271676,  0.74578298],
       [-0.24821586, -0.6732591 ,  0.96852265,  0.13143131],
       [ 0.68785408, -0.31519547, -0.51703849,  0.19271355],
       [ 0.57745079, -0.45648626, -0.11092062, -0.70973502],
       [-0.55082361, -0.04682757,  0.94075562, -0.47297238],
       [-0.79759045,  0.11761374,  0.82962378, -0.27870257],
       [ 0.28243315,  0.12212858, -0.3326572 ,  0.43715446],
       [-0.13257041, -0.26767291, -0.03176485,  0.10682797],
       [ 0.72270836,  0.28516922,  0.02257274, -0.32949923],
       [-0.25998299, -0.51253429,  0.85025723, -0.29722114],
       [ 0.83219463,  0.41082002,  0.88170289,  0.25538391],
       [ 0.41617413, -0.61290292,  0.39331692,  0.32730706],
       [ 0.19060749,  0.29072283, -0.8288495 , -0.05191672],
       [-0.48805989, -0.20919925,  0.73616019,  0.12568742],
       [-0.37915332,  0.862972  , -0.40633382,  0.46752736],
       [ 0.31518433, -0.

In [8]:
classic2.reservoir_state

array([ 9.09091849e-01,  4.16175380e-01,  9.67003224e-01, -4.51108686e-01,
       -8.27538334e-01,  1.05434178e-01, -4.65829868e-01, -1.78620264e-01,
        5.03602341e-01,  3.54103621e-01,  7.80774149e-01, -8.18074317e-01,
        7.34731798e-01, -3.88378215e-01,  9.09077673e-01,  7.88285372e-01,
        7.43498195e-01,  9.05366373e-01,  6.63630168e-01,  9.97066061e-01,
       -7.68197903e-02, -4.68916340e-02,  3.57661892e-01, -7.05601194e-01,
       -1.73174620e-01, -1.51323541e-02,  9.00118086e-01, -4.35506940e-01,
       -4.14940052e-01,  7.38018870e-01,  3.27178970e-01, -4.86522592e-01,
       -7.47490555e-01, -8.78722631e-01,  2.81499477e-01,  3.04471522e-01,
       -6.66818537e-01,  9.10136648e-01,  7.26078951e-04, -9.31789267e-02,
       -6.63671653e-02,  8.42781062e-01,  4.42130784e-01,  1.01105581e-01,
       -8.44177128e-01,  5.18679451e-01, -2.36421284e-01, -6.08136490e-02,
        8.12038585e-01, -3.00827765e-01,  4.26964395e-01,  3.24869060e-01,
       -8.41163892e-01,  

In [4]:
classic = Reservoir(reservoir_size_=4, spatial_multiplexing_=32)
classic.add_performance_task(NARMA(degree_=6))
classic.generate_inputs([1000,3000,5000])
classic.evolve_reservoir('task1', 'full')
classic.results['task1']

[[-0.7595153   0.604195    0.98609298 ...  0.98609298 -0.01926979
   1.        ]
 [ 0.83198747 -0.74510459  0.60779097 ...  0.60779097 -0.36729468
   1.        ]
 [-0.75346169  0.60689528  0.98602353 ...  0.98602353 -0.01356364
   1.        ]
 ...
 [ 0.83353822 -0.73808309  0.60329969 ...  0.60329969 -0.36421218
   1.        ]
 [-0.75250604  0.60494237  0.98588476 ...  0.98588476 -0.02220936
   1.        ]
 [ 0.82702729 -0.73706759  0.61239857 ...  0.61239857 -0.36860992
   1.        ]]
[np.float64(0.34070171532217647), np.float64(0.09602454800036359), np.float64(0.08832125095924435), np.float64(0.11333271693970438), np.float64(0.1366414300119531), np.float64(0.06040228099275204), np.float64(-0.02779859006237488), np.float64(-0.022139281249997162), np.float64(-0.03208899632827776), np.float64(0.07704605890069566), np.float64(0.026337813650832077), np.float64(-0.22469407015287068), np.float64(-0.044423907564487025), np.float64(0.07467645022123134), np.float64(0.055957710777415355), np.f

LinAlgError: Singular matrix

In [5]:
classic = Reservoir(reservoir_size_=128)
classic.add_performance_task(NARMA(degree_=6))
classic.generate_inputs([1000,3000,5000])
classic.evolve_reservoir('task1', 'full')
classic.results['task1']

[[-0.33141954 -0.33998411  0.55123741 ... -0.6522109  -0.27482989
   1.        ]
 [-0.29363592 -0.36628401  0.49723917 ... -0.66841638 -0.35555088
   1.        ]
 [-0.37273591 -0.36230645  0.5720512  ... -0.62077574 -0.33595943
   1.        ]
 ...
 [-0.38550924 -0.34884537  0.58542168 ... -0.65056718 -0.31701525
   1.        ]
 [-0.35775636 -0.3685887   0.56423083 ... -0.65002063 -0.29268641
   1.        ]
 [-0.33238977 -0.36039334  0.54509612 ... -0.65585978 -0.31595004
   1.        ]]
[np.float64(0.1878037230337213), np.float64(0.14054972364707138), np.float64(-0.2031879392985363), np.float64(-0.2687988146539548), np.float64(-0.011111816478173553), np.float64(-0.02156671737624599), np.float64(0.04077126971464247), np.float64(0.21448686160783542), np.float64(-0.049888767371867065), np.float64(-0.04333604862784253), np.float64(0.008407165015111809), np.float64(-0.057216896786459165), np.float64(0.025388818528034058), np.float64(0.052898077673288926), np.float64(-0.039869381033983665), 

('NARMA(6, 0.3, 0.05, 0.375, 0)', np.float64(0.006422016986459298))

In [ ]:
for i in range(50):
    jeps = Reservoir(128, 0.9, 0.1)
    jeps.add_performance_task(NARMA(degree_=6))
    jeps.generate_inputs([1000,5000,3000])
    jeps.evolve_reservoir('task1', 'full')
    #print(jeps.results['task1'])

('NARMA(6, 0.3, 0.05, 0.375, 0)', np.float64(0.005168055004892803))
('NARMA(6, 0.3, 0.05, 0.375, 0)', np.float64(0.006292511244175198))
('NARMA(6, 0.3, 0.05, 0.375, 0)', np.float64(0.003975540911002655))
('NARMA(6, 0.3, 0.05, 0.375, 0)', np.float64(0.007739959755039222))
('NARMA(6, 0.3, 0.05, 0.375, 0)', np.float64(0.006373848639793541))
('NARMA(6, 0.3, 0.05, 0.375, 0)', np.float64(0.014489314342644239))
('NARMA(6, 0.3, 0.05, 0.375, 0)', np.float64(0.006768906787507475))
('NARMA(6, 0.3, 0.05, 0.375, 0)', np.float64(0.007788585805035482))
('NARMA(6, 0.3, 0.05, 0.375, 0)', np.float64(0.006468772165372945))
('NARMA(6, 0.3, 0.05, 0.375, 0)', np.float64(0.006388090369046326))
('NARMA(6, 0.3, 0.05, 0.375, 0)', np.float64(0.010035361881841906))
('NARMA(6, 0.3, 0.05, 0.375, 0)', np.float64(0.00533317531758512))
('NARMA(6, 0.3, 0.05, 0.375, 0)', np.float64(0.00744932697656656))


KeyboardInterrupt: 